apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginxbyhelm
  namespace: default
spec:
  releaseName: nginxbyhelm
  chart:
    spec:
      chart: nginxbyhelm
      sourceRef:
        kind: HelmRepository
        name: nginxbyhelm
  interval: 1m
  install:
    remediation:
      retries: 3
