apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-test
  namespace: kb-poc
  labels:
    app: alpine
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: harbor.tanzukorea.net/bitnami/nginx-exporter:0.10.0-debian-10-r144
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        name: alpine
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
      restartPolicy: Always
