apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-test
  namespace: default
  labels:
    app: alpine
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: nginx:1.19.8-alpine
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        name: alpine
        securityContext:
          runAsUser: 2000
          allowPrivilegeEscalation: false
      restartPolicy: Always
